- hosts: app_servers
  gather_facts: false  # faster; turn on later if you need facts
  become: false        # you're already root

  tasks:
    - name: Pull latest code
      ansible.builtin.command: git pull
      args:
        chdir: /root/ppovsclassical

    - name: Build app with npm (via nvm)
      ansible.builtin.shell: |
        . /root/.nvm/nvm.sh
        cd /root/ppovsclassical
        npm run build
      args:
        executable: /bin/bash

    - name: Copy built files to web root
      ansible.builtin.copy:
        src: /root/ppovsclassical/build/
        dest: /var/www/html/
        remote_src: true
        # owner: www-data   # uncomment if you want
        # group: www-data   # a specific owner/group